nihe-mart: 3.0.0
info:
  title: Backend API
  description: API documentation for the backend of the nihe mart
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /account:
    post:
      summary: Admin registration
      description: Register a new user with email confirmation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: User registered successfully. Please check your email for confirmation.
        '400':
          description: Email already registered or missing fields.
        '500':
          description: Internal server error during registration.
  # /confirm/{token}:
  #   get:
  #     summary: Confirm email
  #     description: Confirm user's email address using the confirmation token
  #     parameters:
  #       - in: path
  #         name: token
  #         schema:
  #           type: string
  #         required: true
  #         description: Confirmation token received via email.
  #     responses:
  #       '200':
  #         description: Email confirmed. You can now log in.
  #       '404':
  #         description: Invalid token or user not found.
  #       '500':
  #         description: Internal server error during email confirmation.
  /auth/login:
    post:
      summary: User login
      description: Log in an existing admin and get JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: JWT token generated successfully.
        '401':
          description: Invalid email, email not confirmed, or invalid password.
        '500':
          description: Internal server error during login.
  /contact:
    post:
      summary: Submit contact form
      description: Submit a contact form with name, email, and message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                message:
                  type: string
              required:
                - name
                - email
                - message
      responses:
        '200':
          description: Contact form submitted successfully.
        '400':
          description: Missing fields in the contact form.
        '500':
          description: Internal server error during contact form submission.
  /contact/{id}:
    delete:
      summary: Delete contact query
      description: Delete a contact query by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the contact query to be deleted.
      responses:
        '200':
          description: Contact query deleted successfully.
        '404':
          description: Contact query not found.
        '500':
          description: Internal server error during contact query deletion.
  /contact/{id}/reply:
    post:
      summary: Reply to contact query
      description: Reply to a contact query by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the contact query to be replied to.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reply:
                  type: string
              required:
                - reply
      responses:
        '200':
          description: Reply sent successfully.
        '404':
          description: Contact query not found.
        '500':
          description: Internal server error during reply to contact query.
